/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agile1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tea Evon
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    public String getRes(int i)
    {
        String resName = "";
        try{
            
            String host = "jdbc:derby://localhost:1527/collegedb";
            String username = "nbuser";
            String password = "nbuser";
            Connection con = DriverManager.getConnection(host, username, password);
            PreparedStatement pstmt = con.prepareStatement("Select * from restaurant where resID=?");
 
            pstmt.setInt(1,i);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
                resName = rs.getString(2);
            }
            
            
//            pstmt.setInt(1,Integer.parseInt(jLabel1.getText()));
//            ResultSet rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName1.setText(rs.getString(2));
//            }
//            pstmt.setInt(1,Integer.parseInt(jLabel2.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName2.setText(rs.getString(2));
//            }       
//            pstmt.setInt(1,Integer.parseInt(jLabel3.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName3.setText(rs.getString(2));
//            }
//            pstmt.setInt(1,Integer.parseInt(jLabel4.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName4.setText(rs.getString(2));
//            }
//            pstmt.setInt(1,Integer.parseInt(jLabel5.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName5.setText(rs.getString(2));
//            }
//            pstmt.setInt(1,Integer.parseInt(jLabel6.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName6.setText(rs.getString(2));
//            }       
//            pstmt.setInt(1,Integer.parseInt(jLabel7.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName7.setText(rs.getString(2));
//            }
//            pstmt.setInt(1,Integer.parseInt(jLabel8.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName8.setText(rs.getString(2));
//            }
//            
//            pstmt.setInt(1,Integer.parseInt(jLabel9.getText()));
//            rs = pstmt.executeQuery();
//            if(rs.next())
//            {
//                jlResName9.setText(rs.getString(2));
//            }
            
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            //Logger.getLongger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return resName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTop = new javax.swing.JPanel();
        jbSearch = new javax.swing.JButton();
        jlArea = new javax.swing.JLabel();
        cbArea = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jpBukitBintang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlResName1 = new javax.swing.JLabel();
        jlResName2 = new javax.swing.JLabel();
        jlResName3 = new javax.swing.JLabel();
        jlResName4 = new javax.swing.JLabel();
        jpSetapak = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlResName5 = new javax.swing.JLabel();
        jlResName6 = new javax.swing.JLabel();
        jlResName7 = new javax.swing.JLabel();
        jlResName8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });
        jpTop.add(jbSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jlArea.setText(" Area :");
        jpTop.add(jlArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 62, 23));

        cbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bukit Bintang", "Setapak", " " }));
        jpTop.add(cbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, -1));

        jPanel1.setLayout(new java.awt.CardLayout());

        jpBukitBintang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\585b-c.jpg")); // NOI18N
        jLabel1.setText("111");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jpBukitBintang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\Mikura-Sushi-c.jpg")); // NOI18N
        jLabel2.setText("112");
        jLabel2.setToolTipText("");
        jpBukitBintang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 220, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\chicken-cc.jpg")); // NOI18N
        jLabel3.setText("113");
        jpBukitBintang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\foodpanda-Halal-dish-3-c.jpg")); // NOI18N
        jLabel4.setText("114");
        jpBukitBintang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 140));

        jlResName1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpBukitBintang.add(jlResName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 20));

        jlResName2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpBukitBintang.add(jlResName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 170, 20));

        jlResName3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpBukitBintang.add(jlResName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 20));

        jlResName4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpBukitBintang.add(jlResName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 20));

        jPanel1.add(jpBukitBintang, "card2");

        jpSetapak.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\Chinese-Featured-c.jpg")); // NOI18N
        jLabel5.setText("115");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jpSetapak.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\Mancare-chinezeasca-foodpanda-c.jpg")); // NOI18N
        jLabel6.setText("116");
        jpSetapak.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 220, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\p bistro-.jpg")); // NOI18N
        jLabel7.setText("117");
        jpSetapak.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tea Evon\\Pictures\\Agile\\Resepi-Lamb-Chop-Homemade-.jpg")); // NOI18N
        jLabel8.setText("118");
        jpSetapak.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, 140));

        jlResName5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpSetapak.add(jlResName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 20));

        jlResName6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpSetapak.add(jlResName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 170, 20));

        jlResName7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpSetapak.add(jlResName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 20));

        jlResName8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jpSetapak.add(jlResName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 20));

        jPanel1.add(jpSetapak, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTop, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        // TODO add your handling code here:
        if(cbArea.getSelectedItem()=="Bukit Bintang")
        {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();

            jPanel1.add(jpBukitBintang);
            jPanel1.repaint();
            jPanel1.revalidate();
            
            jlResName1.setText(getRes(Integer.parseInt(jLabel1.getText())));
            jlResName2.setText(getRes(Integer.parseInt(jLabel2.getText())));
            jlResName3.setText(getRes(Integer.parseInt(jLabel3.getText())));
            jlResName4.setText(getRes(Integer.parseInt(jLabel4.getText())));
            
        }
        
        else if(cbArea.getSelectedItem()=="Setapak")
        {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();

            jPanel1.add(jpSetapak);
            jPanel1.repaint();
            jPanel1.revalidate();
            //getRes();
            
            jlResName5.setText(getRes(Integer.parseInt(jLabel5.getText())));
            jlResName6.setText(getRes(Integer.parseInt(jLabel6.getText())));
            jlResName7.setText(getRes(Integer.parseInt(jLabel7.getText())));
            jlResName8.setText(getRes(Integer.parseInt(jLabel8.getText()))); 
        }
        

    }//GEN-LAST:event_jbSearchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       //new JFMenuItem();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbSearch;
    private javax.swing.JLabel jlArea;
    private javax.swing.JLabel jlResName1;
    private javax.swing.JLabel jlResName2;
    private javax.swing.JLabel jlResName3;
    private javax.swing.JLabel jlResName4;
    private javax.swing.JLabel jlResName5;
    private javax.swing.JLabel jlResName6;
    private javax.swing.JLabel jlResName7;
    private javax.swing.JLabel jlResName8;
    private javax.swing.JPanel jpBukitBintang;
    private javax.swing.JPanel jpSetapak;
    private javax.swing.JPanel jpTop;
    // End of variables declaration//GEN-END:variables
}
